language: ruby
rvm:
- 2.1
# Assume bundler is being used, install step will run `bundle install`.
script: 
 - jekyll build
 - bundle exec htmlproof ./_site --only-4xx --ext --check-html --verbose

# branch whitelist
branches:
  only:
  - develop     # test the gh-pages branch